import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Provider from "@/provider/provider"
import { Toaster } from "@/components/ui/sonner"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {

  return (
    <Provider>
      <html lang="pt-br">
        <body className={inter.className}>{children}</body>
        <Toaster />
      </html>
    </Provider>
  )
}
